#!/usr/bin/env python3
import numpy as np
import torch
from sbi.utils import BoxUniform

from simulator import simulator_trajectory

def eval_accuracy_trajectory(N: int, sim_cfg: dict, prior: BoxUniform, posterior) -> None:
    """
    Evaluate the trained posterior on a CSV dataset generated by generate_dataset.py.

    CSV format: kappa, d_tau, angle_1, ..., angle_M (angles in radians).

    For each row, treat the angle sequence as observed x_o and compute posterior
    samples; use the posterior mean as the point estimate.

    Prints metrics for kappa and d_tau.
    """
    est, true = [], []
    for _ in range(N):
        theta_true = prior.sample()
        true.append(theta_true)
        x_o = simulator_trajectory(theta_true.unsqueeze(0), sim_cfg=sim_cfg)
        samples = posterior.sample(torch.Size([100]), x_o)
        mean_est = samples.mean(dim=0)
        est.append(mean_est)
    true = torch.stack(true, dim=0)
    est = torch.stack(est, dim=0)
    err = est - true
    mae = err.abs().mean(dim=0)
    rmse = torch.sqrt((err**2).mean(dim=0))
    bias = err.mean(dim=0)
    # Flatten in case an extra singleton dimension sneaks in, so we always
    # have 2 elements: [kappa, d_tau]
    mae = mae.reshape(-1)
    rmse = rmse.reshape(-1)
    bias = bias.reshape(-1)
    # Tabular output
    print("\nPosterior accuracy on trajectory summary time-series:")
    print(f"Test rows: {true.shape[0]}")
    print(f"{'Metric':<8} {'kappa':>12} {'d_tau':>12}")
    print(f"{'-'*8} {'-'*12} {'-'*12}")
    print(f"{'MAE':<8} {mae[0].item():>12.4f} {mae[1].item():>12.4f}")
    print(f"{'RMSE':<8} {rmse[0].item():>12.4f} {rmse[1].item():>12.4f}")
    print(f"{'Bias':<8} {bias[0].item():>12.4f} {bias[1].item():>12.4f}")
